import { CombinedParams } from "../codegen/config";

export const paramsForTest: CombinedParams = {
  wiringPackage: 'wiring',
  extractData: `( status: number | undefined, body: any ) => body.data`,
  optionalsFile: "optionals",
  pagesFile: 'pages',
  focusOnVersion: "someFocusOnVersion",
  commonParams: "CommonIds",
  stateName: "FState",
  commonFile: "common",
  pageDomainsFile: "pageDomains",
  domainsFile: "domains",
  fetchersFile: "fetchers",
  mockFetcherPackage: "mockfetchers",
  dbFetcherPackage: 'dbfetchers',
  controllerPackage: "controllers",
  restsFile: "rests",
  loadRefsFile: 'loadRests',
  pactsFile: "pact.spec",
  samplesFile: "samples",
  emptyFile: "empty",
  renderFile: "render",
  guardReportFile: 'guards',
  urlparams: 'commonIds',
  queriesPackage: 'queries',
  thePackage: 'focuson.data',
  applicationName: 'ExampleApp',
  fetcherPackage: 'fetchers',
  fetcherInterface: 'FFetcher',
  wiringClass: 'Wiring',
  fetcherClass: 'MockFetchers',
  schema: 'someSchema.graphql',
  sampleClass: 'Sample',
  dbPackage: 'db',
  defaultDbName: 'mock',
  mutatorPackage: 'mutator',
  resolversPackage: 'resolvers',
  utilsPackage: 'utils',
  maxTuples: 2,
  theme: 'theme-dark',
  controllerAnnotations: [ "@CrossOrigin()" ],
  endpointAnnotations: [ "@EndPointAnnotation()" ],
  teamName: 'focuson',
  debugLevel: 'debug',
  cssDirectory: undefined,
  ignore429: true
};
