import { CustomerStatus, YesNo } from "../commonEnums";


export const occupationAndIncomeSample = {
    regulatoryReport: 'N',
    mainCustomerName: 'Mr XXXXXXXXXX J ABCD Fred Bloggs',
    jointCustomerName: '',
    mainClientRef: 13606326,
    jointClientRef: -1,
    customerOccupationIncomeDetails: [
        {
            areYou: CustomerStatus.S,
            occupation: 'W045',
            customerDescription: 'XXXXXXXXX',
            ownShareOfTheCompany: '',
            owningSharesPct: '',
            workFor: '',
            employmentType: '',
            annualSalaryBeforeDeduction: '',
            annualIncomeExcludingRent: '',
            regularCommissionBonus: '',
            dateOfEmploymentStart: '',
            otherSourceOfIncome: YesNo.N,
            createdBy: 'THORNEM',
            createdDate: '2007-07-03T10:52:27.000+01:00',
            employerName: '',
            whatTypeOfBusiness: 'Electrical Technical Support',
            whatNameBusiness: 'XXXXXXXXX',
            establishedYear: '2006-04-01T00:00:00.000+01:00',
            annualDrawing3Yrs: 100000,
            empStartDate: '',
            empEndDate: '',
            sePositionHeld: 'DIR',
            occupationCategory: 'SK',
            empEmploymentSeq: 999999,
            empAppRoleSeq: 14648850,
            accountantAppRoleSeq: 14648851,
            currentEmployment: YesNo.N
        },
        {
            areYou: CustomerStatus.S,
            occupation: 'W046',
            customerDescription: 'YYYYYYYYYY',
            ownShareOfTheCompany: '',
            owningSharesPct: '',
            workFor: '',
            employmentType: '',
            annualSalaryBeforeDeduction: '',
            annualIncomeExcludingRent: '',
            regularCommissionBonus: '',
            dateOfEmploymentStart: '',
            otherSourceOfIncome: YesNo.N,
            createdBy: 'GARDENL1',
            createdDate: '2011-07-30T12:07:34.000+01:00',
            employerName: '',
            whatTypeOfBusiness: 'Electrical Technical Support',
            whatNameBusiness: 'YYYYYYYYYY',
            establishedYear: '2006-04-01T00:00:00.000+01:00',
            annualDrawing3Yrs: 100000,
            empStartDate: '',
            empEndDate: '',
            sePositionHeld: 'DIR',
            occupationCategory: 'SK',
            empEmploymentSeq: 3182250,
            empAppRoleSeq: 18326759,
            accountantAppRoleSeq: 18326760,
            currentEmployment: YesNo.N
        },
        {
            areYou: CustomerStatus.S,
            occupation: 'W047',
            customerDescription: 'ZZZZZZZZZZZ',
            ownShareOfTheCompany: '',
            owningSharesPct: '',
            workFor: '',
            employmentType: '',
            annualSalaryBeforeDeduction: '',
            annualIncomeExcludingRent: '',
            regularCommissionBonus: '',
            dateOfEmploymentStart: '',
            otherSourceOfIncome: YesNo.N,
            createdBy: 'HOPKINS1',
            createdDate: '2017-05-18T08:29:20.000+01:00',
            employerName: '',
            whatTypeOfBusiness: 'Electrical Technical Support',
            whatNameBusiness: 'ZZZZZZZZZZZ',
            establishedYear: '2006-04-01T00:00:00.000+01:00',
            annualDrawing3Yrs: 25000,
            empStartDate: '',
            empEndDate: '',
            sePositionHeld: 'DIR',
            occupationCategory: 'SK',
            empEmploymentSeq: 3325437,
            empAppRoleSeq: 19762464,
            accountantAppRoleSeq: 19762465,
            currentEmployment: YesNo.N
        },
        {
            areYou: CustomerStatus.E,
            occupation: 'W048',
            customerDescription: 'AAAAAAAAAAA',
            ownShareOfTheCompany: YesNo.Y,
            owningSharesPct: YesNo.Y,
            workFor: '',
            employmentType: '',
            annualSalaryBeforeDeduction: '',
            annualIncomeExcludingRent: '',
            regularCommissionBonus: '',
            dateOfEmploymentStart: '',
            otherSourceOfIncome: YesNo.Y,
            createdBy: 'CMSFSP8',
            createdDate: '2022-01-28T15:25:18.000+00:00',
            employerName: '',
            whatTypeOfBusiness: 'Testing Laboratory',
            whatNameBusiness: 'AAAAAAAAAAA',
            establishedYear: '2022-01-01T00:00:00.000+00:00',
            annualDrawing3Yrs: 200000,
            empStartDate: '',
            empEndDate: '',
            sePositionHeld: '',
            occupationCategory: 'UN',
            empEmploymentSeq: 3427765,
            empAppRoleSeq: '',
            accountantAppRoleSeq: '',
            currentEmployment: YesNo.Y
        }
    ]
}